# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3c469a71db1a6fab7ec12f9f96ab7c9ca279117669a8a0e0d1a4e3461bcdb7af45f51549d2c71283d64da0614c034ba74aa7c84714ed7f2b7c2445e9b4e3dba

test:
  secret_key_base: 2a7708615a75ce34a033b8da1f2d3f724c4b7b0915fb13b1b5e8fa8d500230051b8525396dc230ea3b3319c8c6fa92e7154921cb0f78eab992f5866567193858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
